services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=DATABASE_URL=postgres://root:rootpassword@db:5432/t2_gcs
      - PORT=8080
    volumes:
      - .:/home/node/app
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpassword
      - POSTGRES_DB=t2_gcs
    ports:
      - "5432:5432"